services:
  postgres:
    image: postgres:16
    container_name: ticketing_postgres
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: maven:3.9-eclipse-temurin-21
    container_name: ticketing_app
    working_dir: /app
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    command: mvn clean spring-boot:run
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

volumes:
  pgdata:
  maven_cache: